language: node_js

node_js:
  - "10"


before_install:
  - "cd server"

install:
  - "npm install"

before_script:
  - "npm run postinstall"

script:
  - "npm run test"

after_success:
  - "npm run coveralls"

cache:
  directories:
    - "server/node_modules"
